// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoknyytimzihihvmhwzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpva255eXRpbXppaGlodm1od3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczODQxNDMsImV4cCI6MjA1Mjk2MDE0M30.Jqq47KDNndEAqsTyZHtHC5rzWMkEPyLlJvO2Kjz12Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);